describe('Currículo Fácil', () => {
  it('Entrando no local da aplicação', () => {
    cy.visit('http://localhost:5173/')

    cy.get('h1').should('contain', 'Currículo Inteligente')
    cy.get('#root > div > form > input[type=text]:nth-child(1)').should('exist')
    cy.get('#root > div > form > input[type=text]:nth-child(1)').type('Leonardo Cunha')
    cy.get('#root > div > form > input[type=tel]:nth-child(2)').should('exist')
    cy.get('#root > div > form > input[type=tel]:nth-child(2)').type('83988447654')
    cy.get('#root > div > form > input:nth-child(3)').should('exist')
    cy.get('#root > div > form > input:nth-child(3)').type('flamenguista.peso@gmail.com')
    cy.get('#root > div > form > textarea:nth-child(4)').should('exist')
    cy.get('#root > div > form > textarea:nth-child(4)').type('https://www.youtube.com/watch?v=hQ01th1G1AE')
    cy.get('#root > div > form > input[type=text]:nth-child(5)').should('exist')
    cy.get('#root > div > form > input[type=text]:nth-child(5)').type('Desenvolvedor Frontend')
    cy.get('#root > div > form > textarea:nth-child(6)').should('exist')
    cy.get('#root > div > form > textarea:nth-child(6)').type('5 anos de experiência como tech leader na magazine luiza, 2 anos de professor de qualidade de software na unifacisa')
    cy.get("#root > div > form > textarea:nth-child(7)").should('exist')
    cy.get("#root > div > form > textarea:nth-child(7)").type('Cypress, React, Node.js, Java, Python, SQL, MongoDB, Docker, Kubernetes, Selenium, Git, Agile, Scrum, Kanban, Test Automation, Continuous Integration, Continuous Deployment, DevOps, Cloud Computing, Microservices, RESTful APIs, GraphQL, Web Development, Mobile Development, UI/UX Design, Performance Optimization, Security Best Practices')
    cy.get("#root > div > form > textarea:nth-child(8)").should('exist')
    cy.get("#root > div > form > textarea:nth-child(8)").type('Graduação completa em Ciência da Computação pela Universidade Federal de Campina Grande, MBA em Engenharia de Software pela PUC-Rio')
    cy.get("#root > div > form > textarea:nth-child(9)").should('exist')
    cy.get("#root > div > form > textarea:nth-child(9)").type('CTFL, AWS Practitioner, Scrum Master, Docker Certified Associate')
    cy.get("#root > div > form > textarea:nth-child(10)").should('exist')
    cy.get("#root > div > form > textarea:nth-child(10)").type('Ingles B2, Portugues Nativo, Espanhol A2')
    cy.get("#root > div > form > button").should('exist')
    cy.get("#root > div > form > button").click()
  })
})